# Generated by Django 5.1.6 on 2025-02-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=1)),
                ('adress', models.CharField(max_length=100)),
                ('payment', models.CharField(choices=[('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('DVD', 'DVD'), ('VHS', 'VHS'), ('Equipos de Video', 'Equipos de Video')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('picture', models.ImageField(upload_to='catalogo_images')),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.product')),
                ('year', models.DateField()),
                ('genre', models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Terror', 'Terror'), ('Ciencia ficción', 'Ciencia ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama')], max_length=30)),
            ],
            bases=('catalogo.product',),
        ),
        migrations.CreateModel(
            name='VHS',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.product')),
                ('year', models.DateField()),
                ('type', models.CharField(choices=[('Película', 'Película'), ('Música', 'Música'), ('Documental', 'Documental'), ('Audible', 'Audible')], max_length=30)),
            ],
            bases=('catalogo.product',),
        ),
        migrations.CreateModel(
            name='VideoEquipments',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.product')),
                ('year', models.DateField()),
            ],
            bases=('catalogo.product',),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.client')),
                ('products', models.ManyToManyField(blank=True, to='catalogo.product')),
            ],
        ),
    ]
